"""Load test for the ingestion path. Drives toward the 00 §5 targets:
steady-state 500 alerts/sec, peak burst 5,000/sec.

Run: ``locust -f tests/load/locustfile.py --host http://localhost:8000``
Record measured numbers in BENCHMARKS.md (Phase 5).
"""

from __future__ import annotations

import uuid

from locust import HttpUser, between, task


class AlertProducer(HttpUser):
    wait_time = between(0.0, 0.05)

    @task
    def post_alert(self) -> None:
        self.client.post(
            "/v1/alerts",
            headers={"Idempotency-Key": str(uuid.uuid4())},
            json={
                "tenant": "load-test",
                "topic": "synthetic",
                "severity": 4,
                "title": "load test alert",
                "body": "generated by locust",
            },
        )
